name: very_good_analysis
version: 2.0.0-nullsafety.0
description: >-
  Very Good Dart analyzer settings and best practices used internally at Very Good Ventures.
repository: https://github.com/VeryGoodOpenSource/very_good_analysis
issue_tracker: https://github.com/VeryGoodOpenSource/very_good_analysis/issues
homepage: https://github.com/VeryGoodOpenSource/very_good_analysis
documentation: https://github.com/VeryGoodOpenSource/very_good_analysis

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  pedantic: ^1.10.0-nullsafety.3